logging:
  level: INFO
  loggers:
    com.logiccache: DEBUG
swagger:
  resourcePackage: com.logiccache.resources
cassandra:
  clusterName: "minimal-cluster"
  contactPoints: ["localhost"]
  keyspace: "library"